### ISSUE TITLE
dolt diff empty output with table filter on newly created tables

### ISSUE THREAD

**Issue by max-hoffman** [dolthub/dolt#1256]
expected behavior:

- `dolt diff <commit> <commit> table` should filter output based on table's namespace

actual behavior:

- added table specifier creates empty diff

reproducing:

- database/table created with doltpy
```python3
import logging

logger = logging.getLogger()
logger.setLevel(logging.WARNING)

from doltpy.core import Dolt
from doltpy.core.write import import_df
import pandas as pd

try:
    dolt = Dolt.init("foo")

    df_v1 = pd.DataFrame({"A": [1,1,1], "B": [1,1,1]})
    df_v2 = pd.DataFrame({"A": [1,1,1,2,2,2], "B": [1,1,1,2,2,2]})

    import_df(dolt, "bar", df_v1.reset_index(), ["index"], "create")
    dolt.add("bar")
    dolt.commit("Initialize bar")

    v1 = list(dolt.log(number="1").keys())[0]

    import_df(dolt, "bar", df_v2.reset_index(), ["index"], "update")
    dolt.add("bar")
    dolt.commit("Add rows to bar")

    v2 = list(dolt.log(number="1").keys())[0]
```
 
- command line diff of two commits:
```bash
    max-hoffman@Maxs-MBP ~/D/s/d/m/d/r/foo (max/integration-pt2)> dolt diff -r sql  2uk3ndbkk7neh8uso8ck2anu366mb2le cldb7pohk69fic3s96de2r3okananr5n
CREATE TABLE `bar` (
  `index` int unsigned NOT NULL,
  `A` int unsigned NOT NULL,
  `B` int unsigned NOT NULL,
  PRIMARY KEY (`index`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO `bar` (`index`,`A`,`B`) VALUES (0,1,1);
INSERT INTO `bar` (`index`,`A`,`B`) VALUES (1,1,1);
INSERT INTO `bar` (`index`,`A`,`B`) VALUES (2,1,1);
INSERT INTO `bar` (`index`,`A`,`B`) VALUES (3,2,2);
INSERT INTO `bar` (`index`,`A`,`B`) VALUES (4,2,2);
INSERT INTO `bar` (`index`,`A`,`B`) VALUES (5,2,2);
CREATE TABLE `baz` (
  `level_0` int unsigned NOT NULL,
  `index` int unsigned NOT NULL,
  `A` int unsigned NOT NULL,
  `B` int unsigned NOT NULL,
  PRIMARY KEY (`level_0`,`index`,`A`,`B`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO `baz` (`level_0`,`index`,`A`,`B`) VALUES (0,0,1,1);
INSERT INTO `baz` (`level_0`,`index`,`A`,`B`) VALUES (1,1,1,1);
INSERT INTO `baz` (`level_0`,`index`,`A`,`B`) VALUES (2,2,1,1);
INSERT INTO `baz` (`level_0`,`index`,`A`,`B`) VALUES (3,3,2,2);
INSERT INTO `baz` (`level_0`,`index`,`A`,`B`) VALUES (4,4,2,2);
INSERT INTO `baz` (`level_0`,`index`,`A`,`B`) VALUES (5,5,2,2);
```

- same command with table filter is empty:
```
max-hoffman@Maxs-MBP ~/D/s/d/m/d/r/foo (max/integration-pt2)> dolt diff -r sql  2uk3ndbkk7neh8uso8ck2anu366mb2le cldb7pohk69fic3s96de2r3okananr5n bar
```

- dependencies/ osx catalina:
```toml
[tool.poetry.dependencies]
python = "^3.8"
astroid = "2.3.3"
boto3 = "1.16.46"
botocore = "1.19.46"
certifi = "2020.12.5"
chardet = "4.0.0"
click = "7.1.2"
cx-Oracle = "8.1.0"
decorator = "4.4.2"
idna = "2.10"
isort = "4.3.21"
jmespath = "0.10.0"
joblib = "1.0.0"
lazy-object-proxy = "1.4.3"
mccabe = "0.6.1"
mysql-connector-python = "8.0.21"
nltk = "3.5"
numpy = "1.19.4"
pandas = "1.2.0"
protobuf = "3.14.0"
psutil = "5.8.0"
psycopg2-binary = "2.8.6"
py = "1.10.0"
pylint = "2.4.4"
python-dateutil = "2.8.1"
pytz = "2020.5"
regex = "2020.11.13"
requests = "2.25.1"
retry = "0.9.2"
s3transfer = "0.3.3"
scikit-learn = "0.24.0"
scipy = "1.6.0"
six = "1.15.0"
sklearn = "0.0"
SQLAlchemy = "1.3.22"
threadpoolctl = "2.1.0"
tqdm = "4.55.0"
urllib3 = "1.26.2"
wrapt = "1.11.2"
jupyter = "^1.0.0"
dolt = "^0.9.0"
metaflow = {path = "../../metaflow"}
httplib2 = "^0.18.1"
doltpy = "^1.1.10"
black = "^20.8b1"
pytest = "^6.2.1"
```
