### ISSUE TITLE
Bug: sql-server fails with TablePlus while introspecting schema due to UUID

### ISSUE THREAD

**Issue by josh-chamberlain** [dolthub/dolt#1662]
A recording of this happening: https://recordit.co/PIZauTONtT

Conversation in Discord: 
<img width="947" alt="Screen Shot 2021-04-29 at 6 00 54 PM" src="https://user-images.githubusercontent.com/30379833/116623824-dac95600-a914-11eb-93f1-7c1b0a5c9492.png">

The repo: https://www.dolthub.com/repositories/pdap/data-intake

The offending UUID: https://www.dolthub.com/repositories/pdap/data-intake/query/master?q=describe+incident_reports&active=Tables

The log: 
```
TRACE: received query SELECT table_name as table_name,column_name as column_name,column_type as column_type FROM information_schema.columns WHERE table_schema='data_intake'AND data_type='enum'
DEBUG: executing query
panic: function: 'uuid' not found
```

The settings: 
<img width="503" alt="Screen_Shot_2021-04-29_at_5 42 19_PM" src="https://user-images.githubusercontent.com/30379833/116623728-af466b80-a914-11eb-9076-6ac3d23e004c.png">

The config.yaml:

```
log_level: trace

behavior:
    read_only: false
    autocommit: true

user:
    name: root
    password: ""

listener:
    host: 127.0.0.1
    port: 12000
    max_connections: 1
    read_timeout_millis: 28800000
    write_timeout_millis: 28800000

databases: []

performance:
  query_parallelism: null
```
