### ISSUE TITLE
Dolt statistics table improperly returns two indexes for the Primary Key 

### ISSUE THREAD

**Issue by VinaiRachakonda** [dolthub/dolt#3144]
The Hospital Price Transparency bounty has a strange property. Consider the following schema

```
| hospitals | CREATE TABLE `hospitals` (
  `cms_certification_num` char(6) NOT NULL,
  `name` varchar(256),
  `address` varchar(256),
  `city` varchar(128),
  `state` char(2),
  `zip5` char(5),
  `beds` int,
  `phone_number` char(10),
  `homepage_url` varchar(2048),
  `chargemaster_url` varchar(2048),
  `last_edited_by_username` varchar(32),
  PRIMARY KEY (`cms_certification_num`),
  CONSTRAINT `user_submits_non_empty_row` CHECK ((((`last_edited_by_username` AND `chargemaster_url`) AND `homepage_url`) OR (((NOT(`last_edited_by_username`)) AND (NOT(`chargemaster_url`))) AND (NOT(`homepage_url`)))))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 |
+-----------+---------------------------------
```

However, the information_schema.statistics table seems to indicate that there are two indexes present on cms_certification_num

```
hospital_price_transparency_v3> select * from information_schema.statistics where table_name = 'hospitals' \G
*************************** 1. row ***************************
table_catalog: def
 table_schema: hospital_price_transparency_v3
   table_name: hospitals
   non_unique: 0
 index_schema: hospital_price_transparency_v3
   index_name: PRIMARY
 seq_in_index: 1
  column_name: cms_certification_num
    collation: A
  cardinality: 5992
     sub_part: NULL
       packed: NULL
     nullable:
   index_type: BTREE
      comment:
index_comment:
   is_visible: YES
   expression: NULL
*************************** 2. row ***************************
table_catalog: def
 table_schema: hospital_price_transparency_v3
   table_name: hospitals
   non_unique: 0
 index_schema: hospital_price_transparency_v3
   index_name: cms_certification_num
 seq_in_index: 1
  column_name: cms_certification_num
    collation: A
  cardinality: 5992
     sub_part: NULL
       packed: NULL
     nullable:
   index_type: BTREE
      comment:
index_comment:
   is_visible: YES
   expression: NULL
```

Loading the same table into MySQL does not have the same property
