### ISSUE TITLE
Official Docker hub image?

### ISSUE THREAD

**Issue by bring-shrubbery** [dolthub/dolt#4463]
## The problem

I would like to be able to run Dolt locally via docker-compose, so that I don't need to mess around with shell scripts too much.

I know that I can already run dolt using docker compose, as described [here](https://docs.dolthub.com/introduction/installation/docker#docker-compose-sql-server), but it requires you to also create a Docker image for building it.

## Ideal solution

Would be great to have an official pre-built image at https://hub.docker.com, so I can just have a docker-compose file that looks something like this when testing:

```yml
services:
  db:
    image: dolthub/dolt
    ports:
      - '3306:3306'
```
