### ISSUE TITLE
Cluster replication does not support authentication or authorization on the replication endpoint.

### ISSUE THREAD

**Issue by reltuk** [dolthub/dolt#4565]
A server configured thus:

```yaml
cluster:
  standby_remotes:
  - name: standby
    remote_url_template: http://dolt-2.db:50051/{database}
  bootstrap_role: standby
  bootstrap_epoch: 1
  remotesapi:
    port: 50051
```

is running a remotesapi endpoint on port `50051` which accepts reads and writes from anywhere.

Currently, if you want to deploy standby replication, you have to put an authn+z proxy in front of port 50051 and you have to route your outbound traffic to the standby remotes through something that can add authentication information on the outbound traffic.

**Comment by reltuk** [comment]
Standby replication now supports TLS and authentication on the replication port. The cluster config fragment accepts:

```yaml
cluster:
    tls_key: "path/to/pem/encoded/key"
    tls_cert: "path/to/pem/encoded/cert/chain"
    tls_ca: "path/to/pem/encoded/trusted/roots"
    server_name_urls: ["AllowedURLSanEntry", "AllowedURLSanEntry"]
    server_name_dns: ["AllowedDNSSanEntry", "AllowedDNSSanEntry"]
```

If `tls_key` and `tls_cert` are present, they will be presented as the server certificate when clients connect.

If `tls_ca` is present, TLS will be required on outbound connections to configured cluster peers, and the certificates in the `tls_ca` file will be used as the trusted roots when establishing those connections. Assertions against SAN URL and DNS entries on the presented certificates from the servers can be configured with the `server_name_*` fields.

mTLS is not used.

Authentication is done through ephemeral private keys signing JWTs that appear in the outbound gRPC calls that cluster servers make to their peers. Those JWTs are authenticated against JWKSes which are served by the peer itself – a server receiving an inbound request will check it against all the keys it trusts which it has fetched from the peers to which it is configured to replicate. This behavior is enabled regardless of whether TLS is configured, but it is only secure if TLS can be used to establish the initial trust when fetching the trusted keys from the peers.
