### ISSUE TITLE
Client Dockerfile—does not know new WORKDIR pattern

### ISSUE THREAD

**Issue by almereyda** [dolthub/dolt#4867]
The `serverDockerfile` has lately c87bb090543e3dcc1353227e31f8ba6c5dddbd0e introduced a `WORKDIR` instruction, in order to have a more deterministic setup of the `dolt` environment.

https://github.com/dolthub/dolt/blob/84c9ee2e977da58b09976f988c851e5b03254015/docker/serverDockerfile#L24

This is not yet available in the client Dockerfile, as of 84c9ee2e977da58b09976f988c851e5b03254015:

- https://github.com/dolthub/dolt/blob/84c9ee2e977da58b09976f988c851e5b03254015/docker/Dockerfile

**Comment by almereyda** [comment]
This is especially useful, since the original commit message from c87bb090543e3dcc1353227e31f8ba6c5dddbd0e reads:

> * Use workdir in order to have the same dir for the server and commandline

And since images for both are separated, this should be replicated.

For now a workaround is to use the server's image instead, which supplies the same binary:

```yaml
version: "3.8"
services:
  cli:
    image: dolthub/dolt-sql-server:latest
    entrypoint: ["/usr/local/bin/dolt"]
    volumes_from:
    - server

  server:
    image: dolthub/dolt-sql-server:latest
    volumes:
    - "${PWD}/.state/dolt-sql-server:/var/lib/dolt"
    - "${PWD}/.state/dolt-servercfg.d:/etc/dolt/servercfg.d"
    - "${PWD}/.state/dolt-doltcfg.d:/etc/dolt/doltcfg.d"
```
