### ISSUE TITLE
`dolt sql-server` fails if `databases` is configured in yaml

### ISSUE THREAD

**Issue by tiagojufr** [dolthub/dolt#5780]
I have a script that works fine in 0.54.2 but starts failing in 0.75.0.

Commands:
```
dolt init --new-format
dolt sql-server --config server.yaml
```
server.yaml:
```
(...)
databases: [{path: ., name: test_db}]
(...)
```

In 0.75.0 I get this error:
```
Starting server with Config HP="localhost:4406"|T="28800000"|R="false"|L="info"
error loading environment 'test_db' at path 'C:\some-path\dolt-server': cannot create NBS store for directory containing chunk journal: C:\some-path\dolt-server\.dolt\noms
```

If then I change the server.yaml to
```
(...)
databases: []
(...)
```
it works fine in both versions but I loose my DB name. Tried changing the `path` to be full instead of relative but that didn't work.
Did the `databases` configuraton changed in version 0.75.0? I don't see any reference in the changelog nor in the documentation.

**Comment by timsehn** [comment]
Thanks for the issue. We'll work on this issue today. Sorry for the inconvenience.

This is symptomatic of a larger problem we have with configuration in general: https://github.com/dolthub/dolt/issues?q=is%3Aopen+is%3Aissue+label%3Aconfiguration. We need to staff a project to rationalize and diocument all the ways to configure Dolt and then document it.

**Comment by jennifersp** [comment]
Hi @tiagojufr, thank you for reporting this issue. Major change introduced in `v0.75.0` was [journaling chunkstore](https://www.dolthub.com/blog/2023-03-08-dolt-chunk-journal/), which it is now enabled by default. I was only able to reproduce the issue by setting `DOLT_DISABLE_CHUNK_JOURNAL` environment variable to non empty value, which disables the chunk journal. 
Is it what you did also? If not, can you provide us more information about your environment set up? 🙂

**Comment by tiagojufr** [comment]
No, I don't have any DOLT env vars defined.
Here are my steps to reproduce:
1. Download https://github.com/dolthub/dolt/releases/download/v0.75.0/dolt-windows-amd64.zip and extract to a folder
2. Add that folder to my PATH variable
3. Create new folder and add a `server.yaml` file with the following content:
```
log_level: info

behavior:
  read_only: false
  autocommit: false
  persistence_behavior: load
  disable_client_multi_statements: false

user:
  name: root
  password: ""

listener:
  host: localhost
  port: 4406
  max_connections: 100
  read_timeout_millis: 28800000
  write_timeout_millis: 28800000
  tls_key: null
  tls_cert: null
  require_secure_transport: null

databases: [{path: ., name: test_db}]

performance:
  query_parallelism: null
```
4. Open cmd on that folder
5. Run the 2 commands in the issue description
6. After running the 2nd command I see the error message reported in the issue description
7. If I repeat these steps with version 0.54.2 it works fine

OS info:
- Edition: Windows 10 Enterprise
- Version: 21H2
- Installed on: ‎20-‎01-‎2022
- OS build: 19044.2846
- Experience: Windows Feature Experience Pack 120.2212.4190.0

Please let me know if you need any extra info, I'm happy to help!
