### ISSUE TITLE
Feature request for supporting health and readiness checks in Dolt DB

### ISSUE THREAD

**Issue by juhosyrjanen** [dolthub/dolt#7428]
Hello,

Requesting support for defining health checks for metrics endpoint in Dolt to support better pod handling in Kubernetes.

We're currently investigating running Dolt in a statefulSet inside EKS and would appreciate if `livenessProbe` and `readinessProbe` objects could be supproted directly withing the Dolt container. eg. support defining the following blocks in Kubernetes manifests.

```yaml 
 livenessProbe:
   httpGet:
   path: /metrics/health
   port: 3308
   initialDelaySeconds: 20
   periodSeconds: 10
   failureThreshold: 5
   successThreshold: 1
```

Endpoint should return a OK 200 response when Dolt is healthy and ready to accept connections. `readinessProbe` could also be added to make sure that traffic is directed to the pod only when Dolt is ready to accept connections.

Could this be something to add to the roadmap?

(Sorry for the edit spam, accidentally published after writing the title :D )

**Comment by timsehn** [comment]
We're happy to investigate this request. @reltuk and @coffeegoddd will look today.

**Comment by coffeegoddd** [comment]
currently the `dolthub/dolt-sql-server` container supports these checks in a similar way to the `mysql` container, where you can do something like:
```yaml
    livenessProbe:
      exec:
        command: ["dolt", "--host", "127.0.0.1", "--port", "3306", "--no-tls", "sql", "-q", "select current_timestamp();"]
      initialDelaySeconds: 60
      periodSeconds: 10
    readinessProbe:
      exec:
        command: ["dolt", "--host", "127.0.0.1", "--port", "3306", "--no-tls", "sql", "-q", "select current_timestamp();"]
      initialDelaySeconds: 40
      periodSeconds: 10
```
