### ISSUE TITLE
prisma migrate dev, generating changes to columns of the date type in loop

### ISSUE THREAD

**Issue by Windol** [dolthub/dolt#8173]
This error is related with https://github.com/prisma/prisma/issues/15788 discussion?

<details><summary>Dolt Environment</summary>
<p>

doltdb/config/servercfg.d/config.yaml
```yml
log_level: info

behavior:
  read_only: false
  autocommit: true
  persistence_behavior: load
  disable_client_multi_statements: false
  dolt_transaction_commit: false
  event_scheduler: "ON"

user:
  name: "user7test"
  password: "password7test"

listener:
  host: 0.0.0.0
  port: 3306
  max_connections: 100
  read_timeout_millis: 28800000
  write_timeout_millis: 28800000
  tls_key: null
  tls_cert: null
  require_secure_transport: null
  allow_cleartext_passwords: null

performance:
  query_parallelism: null

data_dir: /var/lib/dolt

cfg_dir: /etc/dolt/doltcfg.d

metrics:
  labels: {}
  host: null
  port: -1

remotesapi: {}

privilege_file: /var/lib/dolt/.doltcfg/privileges.db

branch_control_file: /var/lib/dolt/.doltcfg/branch_control.db

user_session_vars: []

system_variables:
  secure_file_priv: /var/lib/dolt

jwks: []
``` 
doltdb/initdb/20-create-smshub-database.sql
```sql
CREATE DATABASE IF NOT EXISTS db7test /*\!40100 DEFAULT CHARACTER SET utf8 */;
``` 
doltdb/docker-compose.yml
```yml
services:
  doltdb:
    image: dolthub/dolt-sql-server:latest
    container_name: doltdb.docker.vpn.local
    hostname: doltdb.docker.vpn.local
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/dolt
      - ./config:/etc/dolt
      - ./initdb:/docker-entrypoint-initdb.d
``` 

</p>
</details> 
<details><summary>Steps to reproduce:</summary>
<p>

```bash
git clone https://github.com/dolthub/dolt-prisma-example.git
cd dolt-prisma-example
yarn
```
> yarn install v1.22.21
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> [3/4] Linking dependencies...
> [4/4] Building fresh packages...
> Done in 2.68s.

```bash
echo 'DB_HOST="doltdb.docker.vpn.local"' > .env
echo 'DB_PORT=3306' >> .env
echo 'DB_USER="user7test"' >> .env
echo 'DB_PASSWORD="password7test"' >> .env
echo 'DB_NAME="db7test"' >> .env
echo 'DB_URL="mysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}"' >> .env
npx prisma migrate dev --name init
```
```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "db7test" at "doltdb.docker.vpn.local"

Applying migration `20240730195310_init`

The following migration(s) have been created and applied from new schema changes:

migrations/
  └─ 20240730195310_init/
    └─ migration.sql

Your database is now in sync with your schema.

✔ Generated Prisma Client (v5.15.1) to ./node_modules/@prisma/client in 80ms
```
migrations/20240730195310_init/migration.sql
```sql
-- CreateTable
CREATE TABLE `employees` (
    `emp_no` INTEGER NOT NULL,
    `birth_date` DATETIME(3) NOT NULL,
    `first_name` VARCHAR(14) NOT NULL,
    `last_name` VARCHAR(16) NOT NULL,
    `hire_date` DATETIME(3) NOT NULL,

    PRIMARY KEY (`emp_no`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `departments` (
    `dept_no` CHAR(4) NOT NULL,
    `dept_name` VARCHAR(40) NOT NULL,
    `manager_id` INTEGER NULL,

    UNIQUE INDEX `departments_dept_name_key`(`dept_name`),
    PRIMARY KEY (`dept_no`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `dept_emp` (
    `emp_no` INTEGER NOT NULL,
    `dept_no` CHAR(4) NOT NULL,
    `from_date` DATETIME(3) NOT NULL,
    `to_date` DATETIME(3) NOT NULL,

    PRIMARY KEY (`emp_no`, `dept_no`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `departments` ADD CONSTRAINT `departments_manager_id_fkey` FOREIGN KEY (`manager_id`) REFERENCES `employees`(`emp_no`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `dept_emp` ADD CONSTRAINT `dept_emp_emp_no_fkey` FOREIGN KEY (`emp_no`) REFERENCES `employees`(`emp_no`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `dept_emp` ADD CONSTRAINT `dept_emp_dept_no_fkey` FOREIGN KEY (`dept_no`) REFERENCES `departments`(`dept_no`) ON DELETE CASCADE ON UPDATE CASCADE;
```

</p>
</details>

After the initial migration, even without changing the schemas, when running `prisma migrate dev` again, it remains in a loop generating changes to columns of the date type.
```bash
npx prisma migrate dev
```
```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "db7test" at "doltdb.docker.vpn.local"

✔ Enter a name for the new migration: … teste2
Applying migration `20240730195739_teste2`

The following migration(s) have been created and applied from new schema changes:

migrations/
  └─ 20240730195739_teste2/
    └─ migration.sql

Your database is now in sync with your schema.

✔ Generated Prisma Client (v5.15.1) to ./node_modules/@prisma/client in 84ms
```
migrations/20240730195739_teste2/migration.sql
```sql
-- AlterTable
ALTER TABLE `dept_emp` MODIFY `from_date` DATETIME(3) NOT NULL,
    MODIFY `to_date` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `employees` MODIFY `birth_date` DATETIME(3) NOT NULL,
    MODIFY `hire_date` DATETIME(3) NOT NULL;
```
