### ISSUE TITLE
Can't set a numeric session variable using `user_session_vars` section of config.yaml

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#8672]
With the following `config .yaml`:

```yaml
user_saession_vars:
- user: "root"
   vars:
     "dolt_show_system_tables": 1  
```

I get the folloowing error after connecting to root to that server:
```
ERRO[0023] unable to process ComInitDB: Variable 'dolt_show_system_tables' can't be set to the value of '1'  database=config_blog
```

Same with `autocommit`

```
MySQL [(none)]> select @@autocommit;
ERROR 1105 (HY000): Variable 'autocommit' can't be set to the value of '0'
```

However, string variables seems fine:
```yaml
user_session_vars:
- name: "root"
  vars:
    "version": "the best"
```

And on the client:

```sql
MySQL [(none)]> select @@version;
+-----------+
| @@version |
+-----------+
| the best  |
+-----------+
1 row in set (0.001 sec)
```
