### ISSUE TITLE
mydumper fails in deterministic fashion for large database

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#8718]
Repro:

1. Clone: https://www.dolthub.com/repositories/dolthub/transparency-in-pricing
2. `cd transparency-in-pricing`
3. Make this config.yaml
```yaml
$ cat config.yaml 
log_level: info

behavior:
  read_only: false
  autocommit: true

user:
  name: root
  password: ""

listener:
  host: localhost
  port: 4000
  max_connections: 100
  read_timeout_millis: 28800000
  write_timeout_millis: 28800000
  tls_key: "/Users/timsehn/dolthub/git/dolt/go/libraries/doltcore/servercfg/testdata/chain_key.pem"	
  tls_cert: "/Users/timsehn/dolthub/git/dolt/go/libraries/doltcore/servercfg/testdata/chain_cert.pem"
  require_secure_transport: true
```
4. `$ dolt sql-server --config=config.yaml`

5. In another shell run: `mydumper -h 127.0.0.1 -P 4000 -u root -p '' --protocol tcp --database transparency-in-pricing`

I've run it three times and got the following errors at different positions:
```
** (mydumper:20378): CRITICAL **: 14:01:17.311: Thread 1: Could not read data from transparency-in-pricing.rate to write on export-20250106-133614/transparency-in-pricing.rate.00000.sql at byte 62970454016: TLS/SSL error: unexpected eof while reading
```
```
** (mydumper:83008): CRITICAL **: 15:45:33.797: Thread 3: Could not read data from transparency-in-pricing.rate to write on export-20250106-153337/transparency-in-pricing.rate.00000.sql at byte 36137476096: TLS/SSL error: unexpected eof while reading
```
```
** (mydumper:90304): CRITICAL **: 15:58:41.096: Thread 4: Could not read data from transparency-in-pricing.rate to write on export-20250106-154712/transparency-in-pricing.rate.00000.sql at byte 36305829888: TLS/SSL error: unexpected eof while reading
```

All different file positions. The server is also crashed:

```
INFO[0025] ConnectionClosed                              connectionID=4
INFO[0025] ConnectionClosed                              connectionID=5
INFO[0025] ConnectionClosed                              connectionID=3
zsh: killed     dolt sql-server --config=config.yaml
```
