### ISSUE TITLE
Feature Request: Json Logging

### ISSUE THREAD

**Issue by lucasfcnunes** [dolthub/dolt#8888]
# Description

```yaml
# config.yaml - https://docs.dolthub.com/sql-reference/server/configuration#config.yaml
log_level: info
log_format: json # <<< new feature
# ...
```
